project/api/urls.py
from django.urls import path, include

from .views import FeedbackListCreateAPIView, InteractionViewSet, ProfileViewSet, ContactViewSet
from rest_framework.routers import DefaultRouter

app_name = 'api'

router = DefaultRouter()
router.register('interaction', InteractionViewSet, basename='interactions')
router.register('profile', ProfileViewSet, basename='profiles')
router.register('contact', ContactViewSet, basename='contacts')

urlpatterns = [
    path('', include(router.urls)),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.authtoken')),
    path('feedbacks/', FeedbackListCreateAPIView.as_view(), name='feedback_api'),
]

project/deal/urls.py
from django.urls import path
from .views import deal_list, created_deal

app_name = 'deal'

urlpatterns = [
    path('', deal_list, name = 'deals'),
    path('created_deal/', created_deal, name = 'created_deal'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('property/', include('property.urls')),
    path('api/', include('api.urls')),
    path('auth/', include('profile.urls')),
    path('client/', include('client.urls')),
    path('deal/', include('deal.urls')),
]
# urlpatterns += staticfiles(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/deal/models.py
from django.db import models
from client.models import Contact
from profile.models import Profile


class Deal(models.Model):
    STAGE_CHOICES = (
        ('new', 'Новая'),
        ('pending', 'В ожидании'),
        ('approved', 'Одобрена'),
        ('rejected', 'Отклонена'),
        ('closed', 'Закрыта'),
    )

    stage = models.CharField(max_length=20, choices=STAGE_CHOICES, default='new')
    documents = models.FileField(upload_to='documents/', null=True, blank=True)
    description = models.TextField(blank=True)
    client = models.ForeignKey(Contact, on_delete=models.CASCADE, related_name='deals_created')
    assigned_to = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='deals_assigned', blank=True,
                                    null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.client} - {self.stage}'

project/deal/forms.py
from django import forms
from .models import Deal


class DealForm(forms.ModelForm):
    class Meta:
        model = Deal
        fields = '__all__'

project/deal/views.py
from django.shortcuts import render, redirect
from .forms import DealForm
from client.models import Contact
from profile.models import Profile
from .models import Deal

def created_deal(request):
    if request.method == 'POST':
        form = DealForm(request.POST, request.FILES)
        if form.is_valid():
            deal = form.save(commit=False)
            client = request.POST.get('client_id')
            if client:
                deal.client = Contact.objects.get(user_id=client)
            profile_id = request.POST.get('profile_id')
            if profile_id:
                deal.assigned_to = Profile.objects.get(id=profile_id)
            deal.save()
            return redirect('deal:deals')
        else:
            return redirect('deal:deal_create')
    else:
        form = DealForm()
        return render(request, 'deal/deal_create.html', {'form':form})


def deal_list(request):
    deals = Deal.objects.all().select_related('client', 'assigned_to')
    return render(request, 'deal/deals.html', {'deals':deals})

project/templates/deal/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% block styles %}{% endblock %}
</head>
<body>
    <nav>
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href="{% url 'deal:created_deal' %}">Create Deal</a></li>
        </ul>
    </nav>
    {% block content %}{% endblock %}
</body>
</html>

project/templates/deal/deal_create.html
{% extends 'deal/base.html' %}
{% load static %}

{% block title %}
    Create Deal
{% endblock %}

{% block content %}
    <h1>Create Deal</h1>
    <form method="post" enctype="multipart/form-data" class="styled-form">
        {% csrf_token %}
        <table>
            <tbody>
            <tr>
                <th><label for="id_stage">Stage:</label></th>
                <td>{{ form.stage }}</td>
            </tr>
            <tr>
                <th><label for="id_stage">Client:</label></th>
                <td>{{ form.client }}</td>
            </tr>
            <tr>
                <th><label for="id_stage">Description:</label></th>
                <td>{{ form.description }}</td>
            </tr>
            <tr>
                <th><label for="id_documents">Documents:</label></th>
                <td>{{ form.documents }}</td>
            </tr>
            <tr>
                <th><label for="id_assigned_to">Assigned To:</label></th>
                <td>{{ form.assigned_to }}</td>
            </tr>
            </tbody>
        </table>
        <button type="submit" class="btn btn-primary">Create Deal</button>
    </form>
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% endblock %}

project/templates/deal/deals.html
{% extends 'deal/base.html' %}
{% load static %}

{% block title %}
    Deal List
{% endblock %}

{#{% block styles %}#}
{#    <style>#}
{#        table {#}
{#            width: 100%;#}
{#            border-collapse: collapse;#}
{#        }#}
{##}
{#        th, td {#}
{#            border: 1px solid #ddd;#}
{#            padding: 12px;#}
{#            text-align: left;#}
{#            font-size: 14px;#}
{#        }#}
{##}
{#        th {#}
{#            background-color: #f2f2f2;#}
{#            font-weight: bold;#}
{#        }#}
{##}
{#        tr:nth-child(even) {#}
{#            background-color: #f9f9f9;#}
{#        }#}
{##}
{#        tr:hover {#}
{#            background-color: #f1f1f1;#}
{#        }#}
{##}
{#        .actions {#}
{#            display: flex;#}
{#            justify-content: flex-end;#}
{#            margin-top: 20px;#}
{#        }#}
{##}
{#        .actions a {#}
{#            margin-left: 10px;#}
{#        }#}
{#    </style>#}
{#{% endblock %}#}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
{% endblock %}
{% block content %}
    <h1>Deal List</h1>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Stage</th>
                <th>Documents</th>
                <th>Created By</th>
                <th>Client</th>
                <th>Assigned To</th>
            </tr>
        </thead>
        <tbody>
            {% for deal in deals %}
            <tr>
                <td>{{ deal.id }}</td>
                <td>{{ deal.stage }}</td>
                <td>{{ deal.documents }}</td>
                <td>{{ deal.created_at }}</td>
                <td>{{ deal.client }}</td>
                <td>{{ deal.assigned_to }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}